fruit/urls.py
from django.urls import path

from . import views

app_name = 'fruit'

urlpatterns = [  
    path("", views.index, name="index"),
    path("login/", views.login_view, name='login'),
    path('logout/', views.logout, name='logout'),
    path("signup/", views.signup, name='signup'),
    path("upload/", views.upload, name="upload"),
    path("detail/", views.detail, name="detail"),
    path("fruitlist/", views.fruitlist, name="fruitlist"),
    path("food/<int:id>/", views.food, name="food"),
    path("detail2/<int:id>/", views.detail2, name="detail2"),
    path("delete/<int:id>/", views.delete, name="delete"),
]

fruitdjpj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fruit/', include('fruit.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fruit/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class FruitTable(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    year = models.IntegerField(null=True)
    month = models.IntegerField(null=True)
    day = models.IntegerField(null=True)
    img = models.ImageField(upload_to='images/', blank=True,null=True)
    
class FruitImg(models.Model):
    fruittable = models.ForeignKey(FruitTable, on_delete=models.CASCADE, null=True)
    fruitresult = models.CharField(max_length=100,null=True)
    fruitresult2 = models.IntegerField(null=True)
    
class FruitSugar(models.Model):
    sugar = models.FloatField(null=True)
    fruittable = models.ForeignKey(FruitTable, on_delete=models.CASCADE, null=True)

fruit/views.py
from django.shortcuts import render,redirect ,get_object_or_404
from django.contrib.auth import authenticate, login, logout as auth_logout
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
import numpy as np
from keras.models import load_model
import cv2
from django.core.files.storage import default_storage
from .models import FruitTable,FruitImg,FruitSugar
from django.conf import settings
import os
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor

# Create your views here.
def deep(imgfile):
    model = load_model(os.path.join(settings.BASE_DIR, 'fruit/fruits7-model.h5'))
    
    image = cv2.imread(f'./images/{imgfile}')
    
    # 이미지의 높이와 너비를 구한다.
    height, width, channels = image.shape

    # # 이미지의 픽셀을 배열로 만든다.
    pixels = image.reshape((height, width, channels))

    # # 이미지의 픽셀을 (28, 28, 1)로 바꾼다.
    resized_image = cv2.resize(pixels, (150, 150), interpolation=cv2.INTER_NEAREST)

    # # 이미지의 높이와 너비를 구한다.
    height, width, channels = resized_image.shape

    # # 이미지의 픽셀을 배열로 만든다.
    pixels = resized_image.reshape((height, width, channels))

    pixel_data = np.array(pixels)
    
    a = pixel_data.reshape(1,150,150,3)
    
    preds1 = model.predict(a)
    print(preds1)
    classes = ['사과' ,'포도','감귤' ,'복숭아' , '배' ,'바나나' ,'체리','딸기','수박']
    
    result = classes[np.argmax(preds1)-1]
    result2 = np.argmax(preds1)-1
    return result, result2

def machine():
    #print(FruitImg.objects.values_list())
    #print(FruitImg.objects.values_list().last())
    result = FruitImg.objects.values_list().last()[3]
    #print("result:", result)
    result2 = FruitImg.objects.values_list().last()[2]
    #print("result2:", result2)
    df = pd.read_excel('./fruit/datalab.xlsx')
    df = df.rename(columns={'날짜':'날짜.0'})
    
    apple = df[['날짜.0','사과 당도']]
    pear = df[['날짜.1','배 당도']]
    peach = df[['날짜.2','복숭아 당도']]
    grape = df[['날짜.3','포도 당도']]
    orange = df[['날짜.4','감귤 당도']]
    watermelon = df[['날짜.5','수박 당도']]
    strawberry = df[['날짜.6','딸기 당도']]
    banana = df[['날짜.7','바나나 당도']]
    cherry = df[['날짜.8','체리 당도']]
    
    def yearmonday(fruit, n):
        fruit.insert(loc=0, column='day',value=1)
        fruit.insert(loc=0, column='month',value=1)
        fruit.insert(loc=0, column='year',value=1)
        for i in range(len(fruit)):
            fruit.loc[i,'year']= int(fruit[f'날짜.{n}'][i][0:4])
            fruit.loc[i,'month']= int(fruit[f'날짜.{n}'][i][5:7])
            fruit.loc[i,'day']= int(fruit[f'날짜.{n}'][i][8:10])
        fruit = fruit.drop([f'날짜.{n}'],axis=1)
        return fruit
    
    apple = yearmonday(apple,0)
    pear = yearmonday(pear,1)
    peach = yearmonday(peach,2)
    grape = yearmonday(grape,3)
    orange = yearmonday(orange,4)
    watermelon = yearmonday(watermelon,5)
    strawberry = yearmonday(strawberry,6)
    banana = yearmonday(banana,7)
    cherry = yearmonday(cherry,8)
    fruit_li = [apple,grape,orange,peach,pear,banana,cherry,strawberry,watermelon]
    
    #print(fruit_li)
    
    #print(fruit_li[0])
    
    data = fruit_li[result].drop(f'{result2} 당도', axis=1)
    target = fruit_li[result][f'{result2} 당도']
    X_train, X_test, y_train, y_test = train_test_split(
        data, target)
    
    year = FruitTable.objects.values_list().last()[1]
    month = FruitTable.objects.values_list().last()[2]
    day = FruitTable.objects.values_list().last()[3]
    
    user = [[year, month, day]]
    
    gb = GradientBoostingRegressor(n_estimators=100)
    gb.fit(X_train,y_train)
    
    sugar = round(float(gb.predict(user)),2)
    return sugar

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request,user)
            
            print("로그인 성공")
            return redirect('fruit:index')  # 로그인 후 index로 이동
        else:
            print("로그인 실패")
            messages.error(request, '아이디 또는 비밀번호가 잘못되었습니다.')  # 인증 실패 시 오류 메시지 생성
            return redirect('fruit:login')
    return render(request, 'fruit/login.html', {'user': request.user})

def logout(request):
    auth_logout(request)
    return redirect('fruit:index')

def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        if User.objects.filter(username=username).exists():
            messages.error(request, '중복된 아이디입니다.')  # Error message.
            return render(request, 'fruit/signup.html')

        user = User.objects.create_user(username=username, password=password)
        user.save()
        return redirect(reverse('fruit:login'))

    return render(request, 'fruit/signup.html')
        
def index(request):
    if request.method == 'GET':
        return render(request, 'fruit/index.html')
    
def upload(request):
    if request.method == 'POST':
        year = request.POST.get('year', 0) # year = request.POST['year'] 
        month = request.POST['month']
        day = request.POST['day']
        imgfile = request.FILES['imgfiles']
        print(imgfile)
        
        fruit_table = FruitTable.objects.create(user=request.user, year=year, month=month, day=day, img=imgfile)
        
        fruit_result, fruit_result2 = deep(imgfile)
        
        if fruit_result is None:
            messages.error(request, '이미지를 읽을 수 없습니다.')
            return redirect('fruit:index')
        
        FruitImg.objects.create(fruittable=fruit_table, fruitresult=fruit_result, fruitresult2=fruit_result2)
        
        sugar = machine()
        print("sugar:", sugar)
        print(sugar)
        if sugar < 0:
            sugar = 0
        
        FruitSugar.objects.create(fruittable=fruit_table, sugar=sugar)
        
        return HttpResponseRedirect(reverse('fruit:detail2', args=(fruit_table.id,)))
    
def detail(request):
    fruit = FruitTable.objects.filter(user=request.user).last()
    if fruit:
        fruitlist = FruitImg.objects.values_list().last()[1]
        sugar = FruitSugar.objects.values_list().last()[1]
        fimg = FruitTable.objects.values_list().last()[4]
        year = FruitTable.objects.values_list().last()[1]
        month = FruitTable.objects.values_list().last()[2]
        day = FruitTable.objects.values_list().last()[3]
        id = FruitTable.objects.values_list().last()[0]
        
        if sugar < 0:
            sugar = 0
            
        #print(sugar)
        con = {
            'fruitlist':fruitlist,
            'sugar':sugar,
            'img':fimg,
            'year':year,
            'month':month,
            'day':day,
            'id' : id,
        }
        return render(request, 'fruit/detail.html',con)

def detail2(request,id):
    result = FruitImg.objects.get(id=id)
    
    ymd = FruitTable.objects.get(id=id)
    img = FruitTable.objects.get(id=id).img
    sugar = FruitSugar.objects.get(id=id).sugar
    id = FruitTable.objects.values_list().last()[0]
    
    if sugar < 0:
        sugar = 0
   
    con = {
        'fruitresult':result,
        'ymd':ymd,
        'fruitimg':img,
        'sugar':sugar,
        'id':id,
    }
    return render(request,'fruit/detail2.html',con)

def fruitlist(request):
    fruit_li = FruitTable.objects.filter(user=request.user)
    con = {
        'fruit_li':fruit_li,
    }
    
    return render(request, 'fruit/fruitlist.html',con)

def food(request, id):
    fruit = get_object_or_404(FruitTable, id=id, user=request.user)
    foods = FruitTable.objects.filter(user=request.user)
    result = FruitImg.objects.get(id=id)
    
    context = {
        'fruitresult':result,
        'foods': foods,
        'fruitlist': fruitlist,
    }

    return render(request, 'fruit/food.html', context)

def delete(request,id):
    fruit_table = get_object_or_404(FruitTable, id=id)
    fruit_table_id = fruit_table.id  # 해당 과일 테이블의 ID 저장
    fruit_table.delete()  # 해당 과일 테이블 삭제

    # 연결된 FruitImg 및 FruitSugar도 삭제
    FruitImg.objects.filter(fruittable_id=fruit_table_id).delete()
    FruitSugar.objects.filter(fruittable_id=fruit_table_id).delete()

    return HttpResponseRedirect(reverse('fruit:fruitlist'))

fruit/templates/fruit/detail.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>detail</title>
    <link rel="stylesheet" href="/fruit/styles.css">
</head>
<body>
    <header>
        <h1>과일 상세 정보</h1>
        <div class="container">
            <a href="{% url 'fruit:index'%}">Home</a>
            <a href="{% url 'fruit:fruitlist'%}">List</a>
        </div>
    </header>

    <img class='detailimg' src="/{{ img }}" alt="img" width="620" height="500">
    <br>
    <p><a href="{% url 'fruit:food' id%}">{{fruitlist}}</a></p>
    <br>
    <p>{{ year }}년 {{ month }}월 {{ day }}일의 당도: {{ sugar }}brix(당도)</p>
    <br>
    <input type="button" value="뒤로 가기" onclick="location.href='{% url 'fruit:fruitlist' %}'">

    <footer>
        <div>
            <span>이름: 김건일</span><br>
            <span>이메일: laughsi@naver.com</span><br>
            <span>전화번호: 010-8937-2752</span> 
        </div>
        <div>
            <span>이름: 김세연</span><br>
            <span>이메일: pavv150@naver.com </span><br>
            <span>전화번호: 010-8933-6010</span> 
        </div>
        <div>
            <span>이름: 윤웅수</span><br>
            <span>이메일: woong_soo@daum.net</span><br>
            <span>전화번호: 010-6231-9440</span>
        </div>
        <div>
            <span>이름: 황성연</span><br>
            <span>이메일: tjddus693@naver.com</span><br>
            <span>전화번호: 010-7767-7673</span> 
        </div>
    </footer>
</body>
</html>

fruit/templates/fruit/detail2.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>detail2</title>
    <link rel="stylesheet" href="/fruit/styles.css">
</head>
<body>
    <header>
        <h1>과일 상세 정보</h1>
        <div class="container">
            <a href="{% url 'fruit:index'%}">Home</a>
            <a href="{% url 'fruit:fruitlist'%}">List</a>
        </div>
    </header>

    <img class='detailimg' src="/{{fruitimg}}" alt="img" width="500" height="500">
    <br>
    <p><a href="{% url 'fruit:food' id%}">{{fruitresult.fruitresult}}</a></p>
    <br>
    <p>{{ymd.year}}년 {{ymd.month}}월 {{ymd.day}}일의 당도: {{ sugar }}brix(당도)</p>
    <br>
    <input type="button" value="뒤로 가기" onclick="location.href='{% url 'fruit:fruitlist' %}'">
    <footer>
        <div>
            <span>이름: 김건일</span><br>
            <span>이메일: laughsi@naver.com</span><br>
            <span>전화번호: 010-8937-2752</span> 
        </div>
        <div>
            <span>이름: 김세연</span><br>
            <span>이메일: pavv150@naver.com </span><br>
            <span>전화번호: 010-8933-6010</span> 
        </div>
        <div>
            <span>이름: 윤웅수</span><br>
            <span>이메일: woong_soo@daum.net</span><br>
            <span>전화번호: 010-6231-9440</span>
        </div>
        <div>
            <span>이름: 황성연</span><br>
            <span>이메일: tjddus693@naver.com</span><br>
            <span>전화번호: 010-7767-7673</span> 
        </div>
    </footer>
</body>
</html>

fruit/templates/fruit/food.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Food</title>
    <link rel="stylesheet" href="/fruit/styles.css">
</head>
<body>
    <header>
        <h1>{{fruit.name}} 음식 정보</h1>
        <div class="container">
            <a href="{% url 'fruit:index'%}">Home</a>
            <a href="{% url 'fruit:fruitlist'%}">List</a>
        </div>
    </header>
    <h2>{{fruitresult.fruitresult }}로 만들 수 있는 음식 목록</h2>
    <ul>
        {% for food in foods %}
            <li>{{ food.name }}</li>
        {% endfor %}
    </ul>
    <footer>
        <div>
            <span>이름: 김건일</span><br>
            <span>이메일: laughsi@naver.com</span><br>
            <span>전화번호: 010-8937-2752</span> 
        </div>
        <div>
            <span>이름: 김세연</span><br>
            <span>이메일: pavv150@naver.com </span><br>
            <span>전화번호: 010-8933-6010</span> 
        </div>
        <div>
            <span>이름: 윤웅수</span><br>
            <span>이메일: woong_soo@daum.net</span><br>
            <span>전화번호: 010-6231-9440</span>
        </div>
        <div>
            <span>이름: 황성연</span><br>
            <span>이메일: tjddus693@naver.com</span><br>
            <span>전화번호: 010-7767-7673</span> 
        </div>
    </footer>
</body>
</html>

fruit/templates/fruit/fruitlist.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>list</title>
    <link rel="stylesheet" href="/fruit/styles.css">
</head>
<body>
    <header>
        <h1>과일 정보 리스트</h1>
        <div class="container">
            <a href="{% url 'fruit:index'%}">Home</a>
            <a href="{% url 'fruit:fruitlist'%}">List</a>
        </div>
    </header>
<div class="content">
    {% if fruit_li %}
        <ol>
            {% for f in fruit_li %}
                <li>
                <center class='centerimg' >
                    <a href="{% url 'fruit:detail2' f.id %}"><img class='liimg' src="/{{ f.img }}" alt="img"><br>{{f.year}}년{{f.month}}월{{f.day}}일</a>
                </center>
                    <form class="delform" action="{% url 'fruit:delete' f.id %}" method="post">
                        {% csrf_token %}
                        <input type="submit" value="삭제" >
                    </form>
                </li>
            {% endfor %}
        </ol>
    {% else %}
        <p>목록이 없습니다.</p>
    {% endif %}
    <hr>
    <form class="delform" method="post" >
        {% csrf_token %}
        <input type="button" value="추가하기" onclick="location.href='{% url 'fruit:index' %}'">
    </form>
</div>
    <footer>
        <div>
            <span>이름: 김건일</span><br>
            <span>이메일: laughsi@naver.com</span><br>
            <span>전화번호: 010-8937-2752</span> 
        </div>
        <div>
            <span>이름: 김세연</span><br>
            <span>이메일: pavv150@naver.com </span><br>
            <span>전화번호: 010-8933-6010</span> 
        </div>
        <div>
            <span>이름: 윤웅수</span><br>
            <span>이메일: woong_soo@daum.net</span><br>
            <span>전화번호: 010-6231-9440</span>
        </div>
        <div>
            <span>이름: 황성연</span><br>
            <span>이메일: tjddus693@naver.com</span><br>
            <span>전화번호: 010-7767-7673</span> 
        </div>
    </footer>
</body>
</html>

fruit/templates/fruit/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>과일 정보 입력</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <h1>과일 정보 입력</h1>
        <div class="sign">
            <br>
            {% if user.is_authenticated %}
                <p>안녕하세요, {{ user.username }}님</p>  <!-- 로그인 상태에서 사용자명 표시 -->
                <p><a href="{% url 'fruit:logout' %}">로그아웃</a></p>
            {% else %}
                <p><a href="{% url 'fruit:login' %}">로그인</a></p>
            {% endif%}
        </div>
        <div id="header">
            <div class="container">
                <a href="{% url 'fruit:index'%}">Home</a>
                <a href="{% if user.is_authenticated %}{% url 'fruit:fruitlist' %}{% else %}#{% endif %}">List</a>
            </div>
    </header>
<div class="content">
<form class='fruitform' action="{% url 'fruit:upload' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        수확 년도 : <input type="number" name="year" min="2016" max="2023" title="(2016~2023)년도만 입력하세요 " required>
        <br>
        수확 월 : <input type="number" name="month" min="1" max="12" title="1~12 사이의 숫자만 입력하세요" required>
        <br>
        수확 일 : <input type="number" name="day" min="1" max="31" title="1~31 사이의 숫자만 입력하세요" required>
        <br>
        과일 이미지 : <input class="form-control form-control-lg" id="formFileLg" type="file" name="imgfiles" enctype='multipart/form-data' required>
        <br>
        <input type="submit" value="클릭">
</form> 
</div>
<footer>
    <div>
        <span>이름: 김건일</span><br>
        <span>이메일: laughsi@naver.com</span><br>
        <span>전화번호: 010-8937-2752</span> 
    </div>
    <div>
        <span>이름: 김세연</span><br>
        <span>이메일: pavv150@naver.com </span><br>
        <span>전화번호: 010-8933-6010</span> 
    </div>
    <div>
        <span>이름: 윤웅수</span><br>
        <span>이메일: woong_soo@daum.net</span><br>
        <span>전화번호: 010-6231-9440</span>
    </div>
    <div>
        <span>이름: 황성연</span><br>
        <span>이메일: tjddus693@naver.com</span><br>
        <span>전화번호: 010-7767-7673</span> 
    </div>
</footer>
</body>
</html>

fruit/templates/fruit/login.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>로그인</title>
    <link rel="stylesheet" href="/fruit/styles.css">
</head>
<body>
    <header>
        <h1>로그인</h1>
    {% if error_message %}
        <p>{{ error_message }}</p>
    {% endif %}
    </header>
<div class="content">
<form class='loginform' method="post" >
        {% csrf_token %}
        {% if messages %}
        <script>
            {% for message in messages %}
                alert("{{ message }}");
            {% endfor %}
        </script>
        {% endif %}
        아이디: <input type="text" name="username" required><br>
        비밀번호: <input type="password" name="password" required><br>
        <input type="submit" value = "로그인"><br>
        <hr><br>
        <input type="button" value="회원가입" onclick="location.href='{% url 'fruit:signup' %}'">
</form>
</div>
<footer>
    <div>
        <span>이름: 김건일</span><br>
        <span>이메일: laughsi@naver.com</span><br>
        <span>전화번호: 010-8937-2752</span> 
    </div>
    <div>
        <span>이름: 김세연</span><br>
        <span>이메일: pavv150@naver.com </span><br>
        <span>전화번호: 010-8933-6010</span> 
    </div>
    <div>
        <span>이름: 윤웅수</span><br>
        <span>이메일: woong_soo@daum.net</span><br>
        <span>전화번호: 010-6231-9440</span>
    </div>
    <div>
        <span>이름: 황성연</span><br>
        <span>이메일: tjddus693@naver.com</span><br>
        <span>전화번호: 010-7767-7673</span> 
    </div>
</footer>
</body>
</html>

fruit/templates/fruit/signup.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>회원가입</title>
    <link rel="stylesheet" href="/fruit/styles.css">
</head>
<body>
    <header>
        <h1>회원가입</h1>
    </header>
<div class="content">
    <form class='loginform' method="post">
        {% csrf_token %}
        {% if messages %}
        <script>
        {% for message in messages %}
            alert("{{ message }}");
        {% endfor %}
        </script>
        {% endif %}
        사용할 아이디: <input type="text" name="username" required><br>
        사용할 비밀번호: <input type="password" name="password" required><br>
        <input type="submit" value="회원가입"><br>
        <input type="button" value="뒤로 가기" onclick="location.href='{% url 'fruit:login' %}'">
    </form>
</div>
    <footer>
        <div>
            <span>이름: 김건일</span><br>
            <span>이메일: laughsi@naver.com</span><br>
            <span>전화번호: 010-8937-2752</span> 
        </div>
        <div>
            <span>이름: 김세연</span><br>
            <span>이메일: pavv150@naver.com </span><br>
            <span>전화번호: 010-8933-6010</span> 
        </div>
        <div>
            <span>이름: 윤웅수</span><br>
            <span>이메일: woong_soo@daum.net</span><br>
            <span>전화번호: 010-6231-9440</span>
        </div>
        <div>
            <span>이름: 황성연</span><br>
            <span>이메일: tjddus693@naver.com</span><br>
            <span>전화번호: 010-7767-7673</span> 
        </div>
    </footer>
</body>
</html>